### ISSUE TITLE
change ServerWorld to StructureWorldAccessor 

### ISSUE THREAD

**Issue by RodoFire** [Emafire003/StructurePlacerAPI#1]
Hello,
For my mod that I'm developping, I'm using this mod. I want to use it as well for the world gen. The thing is that the `ServerWorld` cannot be called during world gen while `StructureWorldAcessor` can.
 I'm not using entirely json cause I only use the structure nbt for some part but not the entire feature.
I don't want to take all of your work and create a mod that match this need for only this little change
Thanks in advance.

**Comment by Emafire003** [comment]
I will upload a new version to Modrinth soon 
Edit: Done, 1.1.4

**Comment by RodoFire** [comment]
thanks
